mutation CreateNewUser($firstName: String, $lastName: String, $username: String!, $passwordHash: String!, $email: String!, $dateOfBirth: Date) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  user_insert(data: {firstName: $firstName, lastName: $lastName, username: $username, passwordHash: $passwordHash, email: $email, dateOfBirth: $dateOfBirth})
}

query GetCurrentUserPatient @auth(level: USER) {
  patients(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    firstName
    lastName
    dateOfBirth
    contactNumber
    email
    address
    medicalHistorySummary
  }
}

mutation CreateMedicalRecord($patientId: UUID!, $description: String!, $recordDate: Date!, $type: String!, $dosage: String, $vitalSigns: String, $attachedFiles: [String]) @auth(level: USER) {
  medicalRecord_insert(data: {patientId: $patientId, creatorId_expr: "auth.uid", description: $description, recordDate: $recordDate, type: $type, dosage: $dosage, vitalSigns: $vitalSigns, attachedFiles: $attachedFiles})
}

query ListStaff @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  staffs {
    id
    firstName
    lastName
    specialization
    role
  }
}